#undef RGB_MATRIX_VAL_STEP
#define RGB_MATRIX_VAL_STEP 8

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 16

#define SERIAL_NUMBER "mQy6x/5W3EZw"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

